apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: "YWRtaW4K"
  POSTGRES_PASSWORD: "bXlDb29sUGFzc3dvcmQK"
