apiVersion: v1
kind: Pod
metadata:
  name: mypod-deployement
  namespace: default
  labels:
    app: mypod

spec:
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  subdomain: ingress-mypod
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: mypod-container
    image: samber/hello-world-nodejs
    imagePullPolicy: IfNotPresent
    env:
    - name: PORT
      value: "8080"
    ports:
    - containerPort: 8080
    volumeMounts:
        - mountPath: "/usr/share/mypod/html"
          name: task-pv-storage
